spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/GUI_CRUD_DBMS?allowPublicKeyRetrieval=true&useSSL=false&createDatabaseIfNotExist=true
    username: swcamp
    password: swcamp
  sql:
    init:
      mode: always
      schema-locations: classpath:sql/schema.sql
      # data-locations: classpath:sql/data.sql # Uncomment when data.sql is ready

mybatis:
  mapper-locations: classpath:mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true
    jdbc-type-for-null: NULL

logging:
  level:
    com.team2.dbbuddy: DEBUG
    org.springframework.web: INFO
    org.mybatis: DEBUG
